# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tanshuku_site_development
  username: postgres
  password: password
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: 5432

test:
  <<: *default
  database: tanshuku_site_test
  username: postgres
  password: password
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: 5432

# Railway本番環境用（DATABASE_PUBLIC_URLを使用）
production:
  url: <%= ENV["DATABASE_PUBLIC_URL"] || ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
